services:
  db:
    build:
      context: .
      dockerfile_inline: |
        FROM mysql:8.4.0
        COPY ./_database/db.sql /docker-entrypoint-initdb.d/db.sql
    command: mysqld
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER_HOST: "%"

  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - "8801:80"
    links:
      - db:db

  web:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        # Fill this APP argument with the name of the folder
        APP: CVE_2023_43663
    environment:
      FUZZER_COVERAGE_PATH: /var/www/html/
      FUZZER_COMPRESS: 1
      REQUIRES_DB: 1
    volumes:
      - ../../shared-tmpfs:/shared-tmpfs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8088:80
