<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBSPgYpF\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBSPgYpF/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerBSPgYpF.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerBSPgYpF\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerBSPgYpF\appAppKernelProdContainer([
    'container.build_hash' => 'BSPgYpF',
    'container.build_id' => 'd2f3908f',
    'container.build_time' => 1747139036,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBSPgYpF');
