services:
  db:
    # image: arya/mysql
    build:
      context: .
      dockerfile_inline: |
        FROM mysql:8.4.0
        COPY ./_resources/db.sql /docker-entrypoint-initdb.d/db.sql
    command: mysqld
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER_HOST: "%"
    ports:
      - "8806:3306"

  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - "8801:80"
    links:
      - db:db

  web-wp-wcfm:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        APP: app_wordpress_wcfm
    environment:
      FUZZER_COVERAGE_PATH: /var/www/html/
      FUZZER_COMPRESS: 1
      REQUIRES_DB: 1
    volumes:
      - ../../shared-tmpfs:/shared-tmpfs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8083:80
