services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: dolibarr123
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: dolibarr
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER_HOST: "%"
    ports:
      - "8809:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - dolibarr_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - "8804:80"
    links:
      - db:db
    networks:
      - dolibarr_network

  web-dolibarr:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        APP: Dolibarr
    environment:
      FUZZER_COVERAGE_PATH: /var/www/html/
      FUZZER_COMPRESS: 1
      REQUIRES_DB: 1
      DOLI_DB_HOST: db
      DOLI_DB_USER: dolibarr
      DOLI_DB_PASSWORD: dolibarr123
      DOLI_DB_NAME: dolibarr
      DOLI_ADMIN_LOGIN: admin
      DOLI_ADMIN_PASSWORD: admin123
      DOLI_URL_ROOT: http://localhost:8086
    volumes:
      - dolibarr_html:/var/www/html
      - dolibarr_documents:/var/www/documents
      - ../../shared-tmpfs:/shared-tmpfs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init.sh:/init.sh:ro
    ports:
      - 8086:80
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
    networks:
      - dolibarr_network
    entrypoint: ["/init.sh"]

volumes:
  dolibarr_html:
  dolibarr_documents:
  db:

networks:
  dolibarr_network:
    driver: bridge